### ISSUE TITLE
JSONDecodeError, Seems like Telegraph isn't returning a json response

### ISSUE THREAD

**Issue by Zack-Bloodshot** [mercuree/html-telegraph-poster#17]
I am a regular user and use this great module in my project, still a sudden error occurred 

```Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/app/Sagiri/__main__.py", line 211, in doujin
    post = nyah.post(title = f"{hen.title()}", author = "DontKnow", text = tx)
  File "/app/.heroku/python/lib/python3.9/site-packages/html_telegraph_poster/html_to_telegraph.py", line 147, in post
    result = self.edit()
  File "/app/.heroku/python/lib/python3.9/site-packages/html_telegraph_poster/html_to_telegraph.py", line 164, in edit
    result = _upload_via_api(access_token=self.access_token, path=path or self.path, **params)
  File "/app/.heroku/python/lib/python3.9/site-packages/html_telegraph_poster/html_to_telegraph.py", line 85, in _upload_via_api
    resp = requests.post(api_url + method, params, headers={'User-Agent': user_agent}).json()
  File "/app/.heroku/python/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/app/.heroku/python/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/app/.heroku/python/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/app/.heroku/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

It looks like telegram isnt giving json responses, i still dont know though what is wrong, because it was working for two months as a telegram bot deployed on heroku, so it is a Telegraph server error i guess, but i when i tried it in my terminal it worked perfectly! What could be the problem i am facing, is Telegraph blocking my ip or something? . Please Help if you can Thanks!

**Comment by mercuree** [comment]
it was temporary problem between 20-21 August

**Comment by Zack-Bloodshot** [comment]
yep its was fixed, thanks!
